### ISSUE TITLE
Retitle buttons : Save / Discard Changes

### ISSUE THREAD

**Issue by epheterson** [KraigM/HomeBridgeController#5]
The words 'Upload' and 'Revert' do make sense, but only after sitting and pondering for a moment. For example, there is no file actually being 'uploaded.'

Save Changes and Discard Changes may be clearer strings to use.

**Comment by KraigM** [comment]
I see where you are coming from.  I was just worried about people being confused when the "save" fails because they lost connection to the homebridge.

**Comment by epheterson** [comment]
The popup seems to take care of that situation nicely.

As a side-note, the popup would be nicer if it appeared within the UI instead of atop the UI, like this : 
![disk-utility-first-aid](https://cloud.githubusercontent.com/assets/151483/12941444/4008948a-cf87-11e5-8330-c093b34a53c2.png)

(Should I file a separate bug?)

**Comment by KraigM** [comment]
@epheterson On that last comment, which popup are you talking about?

**Comment by epheterson** [comment]
1. Start HomeBridgeController w/out having homebridge running
2. Click 'Upload Config' 

That popup :)

**Comment by KraigM** [comment]
As part of #4 these buttons are being replaced with menu items as well as being renamed. 

_Upload Config_ is now just _Save_ to better fit with the integration into the document system (in fact I have no choice without hacking in a way to override it lol). To go along with that, _Revert Config_ is now _Reload from Hub_.

Since _Revert To Last Saved_ is already built into the document versioning system (integrated with #4), the only real use for redownloading the config from the hub was when you manually changed it without HBC. Given that plus the fact that Save already has a common shortcut (cmd+S), I don't really see the need for the toolbar buttons anymore so I'm disabling the toolbar for the time being.

Does that all sound good?

**Comment by epheterson** [comment]
Sounds good!

**Comment by KraigM** [comment]
Cool.  Completed and will be in next release (0.4.0)
